config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  
  devise_for :users
  
  get 'pages/index', path: "/index" #to: 'pages#home'
  get 'pages/contactUs', path: '/contact-us'  #to: 'pages#contactUs' as: 'contact-us'
  get 'pages/aboutUs', path: '/about-us' #to: 'pages#aboutUs' as: 'about-us'
  get 'pages/privacyPolicy', path: '/privacy-policy' #to: 'pages#privacyPolicy' as: 'pages#privacyPolicy'
  get 'pages/termsAndConditions', path: '/terms-and-conditions' #to: 'pages#termsAndCoditions' as: 'terms-and-conditions'
  get 'pages/disclaimer', path: '/disclaimer' #to: 'pages#disclaimer' as: 'disclaimer'
  get 'pages/sitemap', path: '/sitemap'  #to: 'pages#sitemap' as: '/sitemap'

  

  resources :posts do#, path: "", only: [:index, :new, :create]
    resources :subscribers, only: [:new, :create]
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :subscriber

  extend FriendlyId
  friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
      new_record?
  end

  validates :title, presence: true, uniqueness: true
  validates :shortdescription, presence: true
  validates :keywords, presence: true
  validates :metadescription, presence: true
  validates :body, presence: true
  validates :date, presence: true

  def to_s 
  	"#{title} #{shortdescription} #{keywords} #{metadescription} #{body} #{date}"
  end

end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
attr_accesssible :subemail, :post
belongs_to :post

validates :subemail, 
			presence: true,
			uniqueness: true,
			format: {
			  		with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i 
			  	}

	def to_s 
  		"#{subemail}"
  	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_admin_controller.rb
class ApplicationPagesController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/application_pages_controller.rb
class ApplicationPagesController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationPagesController
  def index
    @posts = Post.all
  end

  def contactUs
  end

  def aboutUs
  end

  def privacyPolicy
  end

  def termsAndConditions
  end

  def disclaimer
  end

  def sitemap
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :subemail]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def show
    @posts = Post.all

    @post = Post.friendly.subscribers.build
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :shortdescription, :keywords, :metadescription, :body, :date)
    end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
	def create
		@subscriber = Post.find(params[:post_id])
		@subscriber = Post.Subscriber.create(subscriber_params)
			
		 respond_to do |format|
	      if @subscriber.save
	        format.html { redirect_to new_subscriber_path, notice: 'Subscribered successfully.' }
	        format.json { render :new, status: :created, location: new_subscriber_path }
	      else
	        format.html { render action: :new }
	        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
	      end
	    end
	end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Post.Subscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriber_params
      params.require(:subscriber).permit(:subemail, :post_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
def headtitle(title = nil)
  if title.present?
    content_for :title, title
  else
    content_for?(:title) ? APP_CONFIG['default_title'] + ' | ' + content_for(:title) : APP_CONFIG['default_title']
  end
end
  def meta_keywords(tags = nil)
    if tags.present?
      content_for :meta_keywords, tags
    else
      content_for?(:meta_keywords) ? [content_for(:meta_keywords), APP_CONFIG['meta_keywords']].join(', ') : APP_CONFIG['meta_keywords']
    end
  end

  def meta_description(desc = nil)
    if desc.present?
      content_for :meta_description, desc
    else
      content_for?(:meta_description) ? content_for(:meta_description) : APP_CONFIG['meta_description']
    end
  end
end

app/helpers/application_pages_helper.rb
module ApplicationPagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= headtitle %></title>
  <meta name="keywords" content="<%= meta_keywords %>" /> 
  <meta name="description" content="<%= meta_description %>" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-56b85e5005ea5817"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="main-nav-container">
    <div class="main-header top-scroll-menu">
      <div class="container">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid-s"> 
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-pro-navbar-collapse" aria-expanded="false"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                <a href="/"><%= image_tag("pro-icon-logo.png", border:0, alt: "ProfessionalQA.com", class: "pro-icon-box") %> </a> </div>
              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="top-pro-navbar-collapse">
                 <!--<div class="pro-search-box input-group">
                  <input type="text" name="search" id="search" disabled placeholder="Search for..." class="form-control" />
                  <span class="input-group-btn input-group-btn-search">
                  <input alt="Search icon" type="image" src="assets/images/search-icon.png" />
                  </span>
               </div>-->
                <div class="social-icons navbar-nav navbar-right"> <%= link_to image_tag("fb.png", alt: "Facebook", title: "Facebook"), href: "https://www.facebook.com/qa.professional", target: "_blank" %><%= link_to image_tag("tt.png", alt:"Twitter", title:"Twitter"), target:"_blank", href:"https://twitter.com/ProfessionalQA" %> <%= link_to image_tag("lin.png", alt:"LinkedIn", title:"LinkedIn"), target:"_blank", href:"https://www.linkedin.com/in/professionalqa" %> <%= link_to image_tag("gp.png", alt:"Google Plus", title:"Google Plus"), target:"_blank", href:"https://plus.google.com/u/0/109878639147270322851/posts" %> <%= link_to image_tag("pin.png", alt:"Pintrest", title:"Pintrest"), target:"_blank", href:"http://www.stumbleupon.com/stumbler/professionalqa" %> <%= link_to image_tag("su.png", alt:"Stumble Upon", title:"Stumble Upon"), target:"_blank", href:"https://www.linkedin.com/in/professionalqa" %></div>
              </div>
              <!-- /.navbar-collapse --> 
            </div>
            <!-- /.container-fluid --> 
        </nav>
      </div>
    </div>
</div>

<div class="container">
  <div class="second-pro-nov">
    <ul class="nav nav-tabs pull-right">
      <li role="presentation"><%= link_to "Home", pages_index_path%></li>
      <li role="presentation"><%= link_to 'Contact Us', pages_contactUs_path %></li>
      <li role="presentation"><%= link_to 'About Us', pages_aboutUs_path %></li>
      
        <% if user_signed_in? %>
          <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
          </li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path)  %> 
          </li>
          <li>
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>  
        <% end %>
     
    </ul>
  </div>
  <% if notice %>
    <div class="alert alert-info" role="alert">
      <p class="notice"><%= notice %> <%= alert %></p>
    </div>
 <% end %>
 <% if alert %>
    <div class="alert alert-danger" role="alert">
      <p class="alert"><%= alert %></p>
    </div>
 <% end %>
</div>
<!--End Header part-->

<!--Start Content part-->
<div class="container content-area">
	<div class="row">
    <div class="col-sm-12">
	<!--Top Ads one line ads-->
    <!--#include file="includes/onelin-ads.html" -->
    <!--Top Ads one line ads-->
    </div>
    </div>
  <div>
    <%= yield %>   
  </div>
</div>
<!--End Content part-->

<!--Start footer part-->
<div class="footer">
  <div class="container">
    <div class="footer-carousel">
      <div class="footer-head">POSTS PROFESSIONAL QA.COM</div>
      <!-- Controls -->
      <div class="ftr-carousel-btn"> <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev"> <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a> <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next"> <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> <span class="sr-only">Next</span> </a> </div>
      <div id="carousel-example-generic" class="carousel slide" data-interval="false" data-ride="carousel"> 
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <ul class="ftr-post-links">
              <li><a href="ab-testing" title="AB Testing">AB Testing</a></li>
              <li><a href="accessibility-testing" title="Accessibility Testing">Accessibility Testing </a></li>
              <li><a href="alpha-testing" title="Alpha Testing">Alpha Testing</a></li>
              <li><a href="beta-testing" title="Beta Testing">Beta Testing</a></li>
              <li><a href="dynamic-testing" title="Dynamic Testing">Dynamic Testing</a></li>
              <li><a href="functional-testing" title="Functional testing">Functional testing</a></li>
              <li><a href="globalization-and-localization-testing" title="Globalization and Localization testing">Globalization and Localization testing</a></li>
              <li><a href="installation-testing" title="Installation testing">Installation testing</a></li>
              <li><a href="non-functional-testing" title="Non-functional testing">Non-functional testing</a></li>
              <li><a href="sanity-testing" title="Sanity Testing">Sanity Testing</a></li>
              <li><a href="smoke-testing" title="Smoke Testing">Smoke Testing</a></li>
              <li><a href="static-testing" title="Static testing">Static testing</a></li>
              <li><a href="system-testing" title="System Testing">System Testing</a></li>
              <li><a href="agile-testing" title="Agile Testing">Agile Testing</a></li>
              <li><a href="gui-testing" title="GUI Testing">GUI Testing</a></li>
              <li><a href="test-data-and-its-importance" title="Test data and its importance">Test data and its importance</a></li>
              <li><a href="user-acceptance-testing" title="User Acceptance Testing">User Acceptance Testing</a></li>
              <li><a href="exploratory-testing" title="Exploratory Testing">Exploratory Testing</a></li>
              <li><a href="data-warehousing-testing" title="Data Warehousing Testing">Data Warehousing Testing</a></li>
              <li><a href="adhoc-testing" title="ADHOC Testing">ADHOC Testing</a></li>
            </ul>
          </div>
          <div class="item">
            <ul class="ftr-post-links">
              <li><a href="mobile-app-testing" title="Mobile App Testing">Mobile App Testing</a></li>
              <li><a href="content-testing" title="Content Testing">Content Testing</a></li>
              <li><a href="non-functional-testing" title="Non-functional testing">Non-functional testing</a></li>
              <li><a href="stress-testing" title="Stress Sesting">Stress Testing</a></li>
              <li><a href="software-development-life-cycle" title="Software Development Life Cycle">Software Development Life Cycle</a></li>
              <li><a href="acceptance-testing" title="Acceptance Testing">Acceptance Testing</a></li>
              <li><a href="performance-testing" title="Performance testing">Performance testing</a></li>
              <li><a href="conformance-testing" title="conformance testing">Conformance testing</a></li>
              <li><a href="software-quality-assurance" title="Software Quality Assurance">Software Quality Assurance</a></li>
              <li><a href="use-case-testing" title="Use Case Testing">Use Case Testing</a></li>
              <li><a href="test-strategy" title="Test Strategy">Test Strategy</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-second">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-lg-6 col-lg-6">
          <div class="footer-second-box follow-us-box">
            <h1>Follow Us:</h1>
            <div class="social-icons navbar-nav navbar-right"> <%= link_to image_tag("fb-ftr.png", alt: "Facebook", title: "Facebook"), href: "https://www.facebook.com/qa.professional", target: "_blank" %><%= link_to image_tag("tt-ftr.png", alt:"Twitter", title:"Twitter"), target:"_blank", href:"https://twitter.com/ProfessionalQA" %> <%= link_to image_tag("lin-ftr.png", alt:"LinkedIn", title:"LinkedIn"), target:"_blank", href:"https://www.linkedin.com/in/professionalqa" %> <%= link_to image_tag("gp-ftr.png", alt:"Google Plus", title:"Google Plus"), target:"_blank", href:"https://plus.google.com/u/0/109878639147270322851/posts" %> <%= link_to image_tag("pin-ftr.png", alt:"Pintrest", title:"Pintrest"), target:"_blank", href:"http://www.stumbleupon.com/stumbler/professionalqa" %> <%= link_to image_tag("su-ftr.png", alt:"Stumble Upon", title:"Stumble Upon"), target:"_blank", href:"https://www.linkedin.com/in/professionalqa" %> <%= link_to image_tag("rss.png", alt:"Stumble Upon", title:"Stumble Upon"), target:"_blank", href:"#" %></div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-lg-6 col-lg-6">
          <div class="footer-second-box ftr-signup-box">
            <p>We deliver. Get the best of <br />
              <a href="/">Professional QA</a> in your inbox.</p>
            <div class="clearfix">
              <form class="navbar-form navbar-left" role="search">
                <div class="input-group">
                  <input type="text" class="form-control" id="ftr-user-email" placeholder="Enter your email"><span class="input-group-btn"><button type="submit" id="footer-form" class="btn btn-danger">Submit</button></span></div>
              </form>
            </div>
            <p>You can opt-out at any time. See our <a href="privacy-policy">privacy policy</a>.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="copyright">  
  <div class="container">
    	<ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'About Us', pages_aboutUs_path %></li>
          <li><%= link_to 'Privacy Policy', pages_privacyPolicy_path %></li>
          <li><%= link_to 'Terms And Conditions', pages_termsAndConditions_path %></li>
          <li><%= link_to 'Disclaimer', pages_disclaimer_path %></li>
          <li><%= link_to 'Sitemap', pages_sitemap_path %></li>
          <li><%= link_to 'Contact Us', pages_contactUs_path %></li>
        </ul>
        <div class="ctext">&copy; 2016 ProfessionalQA.com - All rights reserved.</div>
      </div>
  </div>
</div>
<!--End footer part-->
</body>
</html>

app/views/pages/aboutUs.html.erb
<h2>About Us</h2>
<hr />
<p>The idea of ProfessionalQA.com was born out of a belief that there should be no barriers in the path to achieving knowledge. Utilising the overwhelming inroads, which the internet has made in reaching the remotest of populations, we aim to become facilitators for change by disseminating the latest from the world of software testing to those who have a never ending thirst for testing. We at ProfessionalQA.com have created a repository of content on a digital platform, touching upon a whole spectrum of subjects from the world of software testing, QA and automation.</p>

<div class="panel panel-info">
	<div class="panel-heading">
		<h3 class="panel-title">Why ProfessionalQA.com?</strong>
</div>
<div class="panel-body"> 
<p><i class="glyphicon glyphicon-ok"></i> <strong>Our Mission:</strong> Knowledge for all</p>
<p><i class="glyphicon glyphicon-ok"></i> <strong>Encyclopedia:</strong> Our coverage encapsulates all the terms and terminologies related to software testing, QA and automation.</p>
<p><i class="glyphicon glyphicon-ok"></i> <strong>Bridging the skill gap:</strong> From greenhorns still learning the nuances of the game to seasoned professionals looking to augment their skill sets, there is something in it for everyone. </p>
<p><i class="glyphicon glyphicon-ok"></i> <strong>What's trending:</strong> Our depository of information is continuously updated with articles on the next BIG thing that's causing waves in the field of QA.</p>
	</div>
</div>

app/views/pages/contactUs.html.erb
<h2>Contact Us</h2>
      <hr />
      <div>
         <div >   
            <form class="well form-horizontal" action=" " method="post"  id="contact_form">
            <fieldset> 
           <!-- Text input-->
            <div class="form-group">
            <label class="col-md-4 control-label">Name*</label>  
            <div class="col-md-4 inputGroupContainer">
            <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <input  name="cntct_name" id="cntct_name" placeholder="Name" class="form-control"  type="text">
            </div>
            </div>
            </div>
            
            <!-- Text input-->
               <div class="form-group">
            <label class="col-md-4 control-label">E-Mail*</label>  
            <div class="col-md-4 inputGroupContainer">
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
            <input name="cntct_email" id="cntct_email" placeholder="E-Mail Address" class="form-control"  type="text">
            </div>
            </div>
            </div>
            
            
            <!-- Text input-->
               
            <div class="form-group">
            <label class="col-md-4 control-label">Phone #</label>  
            <div class="col-md-4 inputGroupContainer">
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
            <input name="cntct_phone" id="cntct_phone" placeholder="(845)555-1212" class="form-control" type="text">
            </div>
            </div>
            </div>
            
            <!-- Text input-->
              
            <div class="form-group">
            <label class="col-md-4 control-label">Message*</label>
            <div class="col-md-4 inputGroupContainer">
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    <textarea class="form-control" name="cntct_message" id="cntct_message" placeholder="Comments"></textarea>
            </div>
            
            <!-- Success message -->
            <br>
            <div class="alert alert-success collapse" role="alert" id="cntct_success_message"></div>
            </div>
            </div>
            <!-- Text input-->
            
            
            
            <!-- Button -->
            <div class="form-group">
            <label class="col-md-4 control-label"></label>
            <div class="col-md-4">
            <button type="submit" class="btn btn-warning" >Send <span class="glyphicon glyphicon-send"></span> <span class="collapse contact-spin glyphicon glyphicon-refresh glyphicon-spin"></span></button>
            </div>
            </div>
            
            </fieldset>
            </form>
            </div>
      </div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
  <div class="col-sm-6 field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="col-sm-6 field form-group">
    <%= f.label :shortdescription %><br>
    <%= f.text_area :shortdescription, class: "form-control" %>
  </div>
</div>
<div class="row">
  <div class="col-sm-6 field form-group">
    <%= f.label :keywords %><br>
    <%= f.text_area :keywords, class: "form-control" %>
  </div>
  <div class="col-sm-6 field form-group">
    <%= f.label :metadescription %><br>
    <%= f.text_area :metadescription, class: "form-control" %>
  </div>
</div>
  <div class="field form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control", :ckeditor => {:uiColor => '#AADC6E'} %>
  </div>
  <div class="field form-group">
    <%= f.label :date %><br>
    <%= f.date_select :date, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>

<div class="table-responsive">
<table class="table table-hover table-bordered table-striped">
  <thead>
    <tr>
      <th>Sr. No.</th>
      <th>Title</th>
      <th width="20%">Short Description</th>
      <th>User</th>
      <th>Date</th>
      <th>View</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    
    <% @posts.each do |post| %>
      
      <tr>
        <td><%= post.id %></td>
        <td><%= post.title %></td>
        <td><%= post.shortdescription %></td>
        <td><% if user_signed_in? %> <%= post.user.email %> <% end %></td>
        <td><%= post.date %></td>
        <td><%= link_to 'Show', post %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% headtitle @post.title %>
<% meta_keywords @post.keywords %>
<% meta_description @post.metadescription %>

<div class="col-sm-9">
  <div class="pro-content-box">
    <h1><%= @post.title %></h1>
    <p class="blog-post-meta"><%= @post.date.strftime("%B") %> <%= @post.date.day %>, <%= @post.date.year %> <br />
    <div class="addthis_native_toolbox"></div>
    <hr>
    <div class="fb-share-button" data-href="https://www.facebook.com/ThinkSysInc/" data-layout="button_count"></div>      
        <!-- Go to www.addthis.com/dashboard to customize your tools -->
    </p>
    <div>
    	<%= simple_format(@post.body) %>
    </div>
  </div>      
  <% if user_signed_in? %>
  <div>
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Back', posts_path %>
  </div>
  <% end %>
</div>

<!--right side bar section -->   
<div class="col-sm-3">
	<div class="alert alert-info subscribe-box">
  <h3>Subscribe Pro QA</h3>
    <%= form_for([@post, Subscriber.build) do |f| %>
      <% if @subscriber.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

        <ul>
        <% @subscriber.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      <div class="input-group">
        <%= f.text_field :subemail, class: "form-control", placeholder: "Enter your email" %>
        <span class="input-group-btn"><%= f.submit 'Submit', class: 'btn btn-primary'  %></span>
      </div>
    <% end %>    
</div>

  <hr>
  <% @posts.each do |post| %>
    <li class="list-group-item"><a href="stress-testing" title="Stress Sesting"><%=link_to post.title, post %></li>
  <% end %>
</div>

app/views/subscribers/new.html.erb
<div class="alert alert-info subscribe-box">
	<h3>Subscribe Pro QA</h3>
    <%= form_for(@subscriber) do |f| %>
    	<% if @subscriber.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

	      <ul>
	      <% @subscriber.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	    <div class="input-group">
	    	<%= f.text_field :subemail, class: "form-control", placeholder: "Enter your email" %>
	    	<span class="input-group-btn"><%= f.submit 'Submit', class: 'btn btn-primary'  %></span>
	    </div>
    <% end %>    
</div>